### ISSUE TITLE
Missing assets/build (and/or the build setup)

### ISSUE THREAD

**Issue by apokalyptik** [aidvu/doner#2]
https://github.com/aidvu/doner/blob/master/index.html#L34

https://cloudup.com/cT8mSatRhpv

**Comment by aidvu** [comment]
@apokalyptik Included built javascript into the repository. Please confirm it's fine now.

**Comment by apokalyptik** [comment]
> sh: 1: cannot create assets/build/bundle.min.js: Directory nonexistent

**Comment by apokalyptik** [comment]
The above was from npm run build. the below is npm run start.  both from a clean pull/checkout

> { [Error: ENOENT, open 'assets/build/bundle.js'] errno: 34, code: 'ENOENT', path: 'assets/build/bundle.js' }

**Comment by aidvu** [comment]
I see. Will fix.

**Comment by aidvu** [comment]
Created an empty build/ dir.
